---
title: "Untitled"
author: "Juan Silva"
date: "2/6/2020"
output: html_document
---

try this

what's going on?

```{r}
# For general stuff:
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
library(paletteer)

# For ts stuff: 
library(tsibble)
library(fable)
library(fabletools)
library(feasts)
library(forecast)

# For spatial stuff: 
library(sf)
library(tmap)
library(mapview)
```

# Monthly US energy consumption (renewables)

```{r}

us_renew <- read_csv(here("data", "renewables_cons_prod.csv")) %>% 
  clean_names()

unique(us_renew$description)



```

We'll focus on consumption data. 

### Clean up data

- Convert description to all lowercase
- Only keep observations for "consumption" in "description" variable
- Remove any "total" observations from "description" variable


```{r}

renew_clean <- us_renew %>% 
  mutate(description = str_to_lower(description)) %>% 
  filter(str_detect(description, pattern = "consumption")) %>% 
  filter(!str_detect(description, pattern = "total"))

```

